project_id = "idicfwwajjifamvlntku"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.analyze-speech]
verify_jwt = false

[functions.deepgram-transcribe]
verify_jwt = false
